#
# GCC based makefile
#
# Copyright 2006-2011 Sam Adams <sea36 at users.sourceforge.net>
#
# This file is part of JNI-InChI.
#
# JNI-InChI is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# JNI-InChI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with JNI-InChI.  If not, see <http://www.gnu.org/licenses/>.

LDFLAGS += -s
CFLAGS += -I"${JAVA_HOME}/include" -I$(INCHI_SRCDIR)
CFLAGS += -Os -ansi -pedantic

$(TARGET): $(INCHI_OBJECTS) $(JNI_OBJECTS)
	$(LINK.c) $^ -o $@

$(INCHI_OBJDIR)/%.o: $(INCHI_SRCDIR)/%.c
	$(COMPILE.c) $< -o $@

$(JNI_OBJDIR)/%.o: $(JNI_SRCDIR)/%.c $(JNI_HEADERS)
	$(COMPILE.c) $< -o $@ -I$(JNI_HEADER_DIR)
